services:
  postgresql:
    image: postgres
    container_name: nest-backend
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=nest-backend
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'
