export const users = [
  {
    _id: '671117c6b84a0a9f387f3624',
    index: 0,
    guid: 'e0f15ece-b71d-48db-a14a-cfaf0065591e',
    isActive: true,
    balance: '$3,958.31',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'brown',
    name: 'Ewing Koch',
    gender: 'male',
    company: 'LUMBREX',
    email: 'ewingkoch@lumbrex.com',
    phone: '+1 (930) 415-3600',
    address: '216 Bridgewater Street, Hartsville/Hartley, New Mexico, 1577',
    about:
      'Officia esse laboris irure eu id ex qui cillum eu magna pariatur tempor enim enim. Exercitation aliquip adipisicing incididunt laboris cillum. Do nisi sunt nisi laboris quis est laborum nostrud velit elit exercitation proident.\r\n',
    registered: '2018-10-04T08:28:52 -05:00',
    latitude: -36.652324,
    longitude: -81.761521,
    tags: ['cupidatat', 'magna', 'amet', 'proident', 'dolore', 'nisi', 'id'],
    friends: [
      {
        id: 0,
        name: 'Taylor Newton',
      },
      {
        id: 1,
        name: 'Hazel Hunt',
      },
      {
        id: 2,
        name: 'Ayers Leblanc',
      },
    ],
    greeting: 'Hello, Ewing Koch! You have 1 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '671117c685b674dae4fb8d74',
    index: 1,
    guid: 'c7c13515-d9c1-4fdb-a5c5-1c89fb962f05',
    isActive: true,
    balance: '$3,570.71',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'blue',
    name: 'Mejia Abbott',
    gender: 'male',
    company: 'HINWAY',
    email: 'mejiaabbott@hinway.com',
    phone: '+1 (974) 489-3812',
    address: '556 Crescent Street, Sutton, Marshall Islands, 6370',
    about:
      'Enim velit eiusmod cillum tempor ipsum fugiat ut incididunt commodo consectetur in in sint aute. Nulla esse mollit eu dolor non aute nulla officia irure non veniam. Qui velit anim culpa sint qui deserunt. Culpa elit tempor sint ut pariatur minim velit incididunt ipsum incididunt Lorem.\r\n',
    registered: '2020-09-17T04:10:34 -05:00',
    latitude: 71.013649,
    longitude: -107.63871,
    tags: ['adipisicing', 'anim', 'eu', 'enim', 'aliqua', 'irure', 'ad'],
    friends: [
      {
        id: 0,
        name: 'Casey Austin',
      },
      {
        id: 1,
        name: 'Mamie Pruitt',
      },
      {
        id: 2,
        name: 'Myra Carney',
      },
    ],
    greeting: 'Hello, Mejia Abbott! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '671117c657c053c41e4b6873',
    index: 2,
    guid: 'e6d272ee-e92c-4aec-aef1-9af2dc40cc8e',
    isActive: false,
    balance: '$2,977.05',
    picture: 'http://placehold.it/32x32',
    age: 35,
    eyeColor: 'blue',
    name: 'Carolina Hunter',
    gender: 'female',
    company: 'AQUAFIRE',
    email: 'carolinahunter@aquafire.com',
    phone: '+1 (894) 430-2686',
    address: '751 Riverdale Avenue, Bath, Oregon, 3895',
    about:
      'Culpa eiusmod cupidatat ipsum in adipisicing veniam est do ullamco veniam nisi officia. Officia Lorem nulla nostrud id sunt. Nostrud esse velit dolor in proident ut. Reprehenderit culpa adipisicing minim tempor deserunt anim duis aute eu aliqua ipsum.\r\n',
    registered: '2020-02-25T02:00:37 -05:00',
    latitude: 82.04903,
    longitude: 169.132274,
    tags: ['sit', 'esse', 'in', 'ad', 'deserunt', 'consectetur', 'ea'],
    friends: [
      {
        id: 0,
        name: 'Harrell Mcdowell',
      },
      {
        id: 1,
        name: 'Guadalupe Hubbard',
      },
      {
        id: 2,
        name: 'Letitia Tate',
      },
    ],
    greeting: 'Hello, Carolina Hunter! You have 10 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '671117c67dff96ea1463831b',
    index: 3,
    guid: '964f2ce3-f36e-4514-bfe4-5e00fc2025d4',
    isActive: true,
    balance: '$1,771.83',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'brown',
    name: 'Eve Ingram',
    gender: 'female',
    company: 'PRIMORDIA',
    email: 'eveingram@primordia.com',
    phone: '+1 (800) 581-2860',
    address: '767 Bennet Court, Geyserville, Northern Mariana Islands, 8225',
    about:
      'Magna adipisicing non proident Lorem fugiat est. Ad ad ullamco velit exercitation. Quis labore laboris et deserunt adipisicing veniam ex officia consequat consequat et deserunt fugiat voluptate. Nostrud Lorem cupidatat velit esse do duis laboris. Qui Lorem occaecat enim anim incididunt pariatur tempor pariatur id aute minim. Voluptate consequat veniam qui id nulla sunt sit labore veniam. Labore duis labore dolor dolor.\r\n',
    registered: '2024-10-06T09:35:55 -05:00',
    latitude: 72.986949,
    longitude: 163.450982,
    tags: ['exercitation', 'dolore', 'laborum', 'sint', 'ea', 'esse', 'non'],
    friends: [
      {
        id: 0,
        name: 'Pauline Bowen',
      },
      {
        id: 1,
        name: 'Bush Robbins',
      },
      {
        id: 2,
        name: 'Douglas Gentry',
      },
    ],
    greeting: 'Hello, Eve Ingram! You have 9 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '671117c6a5acad0e16a16473',
    index: 4,
    guid: '71b10d20-d0d4-499b-a8fb-ece95f9eaa3e',
    isActive: false,
    balance: '$3,291.00',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'brown',
    name: 'Mann Hutchinson',
    gender: 'male',
    company: 'ORBEAN',
    email: 'mannhutchinson@orbean.com',
    phone: '+1 (927) 415-3647',
    address: '424 Herzl Street, Shawmut, North Dakota, 8046',
    about:
      'Magna laborum dolor exercitation ad. Duis excepteur sit mollit excepteur dolore officia tempor sint nisi. Culpa quis aute reprehenderit laboris nisi ipsum quis. Eiusmod et veniam ullamco consequat enim officia incididunt ex Lorem id nisi.\r\n',
    registered: '2017-06-07T07:52:36 -05:00',
    latitude: -69.349462,
    longitude: 118.938829,
    tags: ['aliquip', 'et', 'elit', 'ex', 'pariatur', 'officia', 'esse'],
    friends: [
      {
        id: 0,
        name: 'Carmella Ware',
      },
      {
        id: 1,
        name: 'Regina Harris',
      },
      {
        id: 2,
        name: 'Miles Harding',
      },
    ],
    greeting: 'Hello, Mann Hutchinson! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '671117c6e30cb7a630ace48f',
    index: 5,
    guid: '9fb1599e-5165-4ecc-8be7-86c8b4a0c166',
    isActive: true,
    balance: '$2,783.41',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: 'Kelsey Melton',
    gender: 'female',
    company: 'QUALITERN',
    email: 'kelseymelton@qualitern.com',
    phone: '+1 (866) 491-3527',
    address: '572 Battery Avenue, Delco, Virgin Islands, 8141',
    about:
      'Proident ut deserunt qui elit fugiat amet ad et qui. Eu ea anim dolore officia ad fugiat labore dolor cillum nulla officia veniam sint est. Eiusmod non pariatur quis elit. Laboris anim culpa ad fugiat adipisicing culpa. Elit sint voluptate minim ex id amet cillum occaecat tempor cillum. Occaecat nostrud excepteur consectetur elit labore nostrud.\r\n',
    registered: '2014-10-21T11:29:55 -06:00',
    latitude: 19.70761,
    longitude: -161.573804,
    tags: ['dolor', 'eu', 'do', 'dolor', 'ullamco', 'nostrud', 'magna'],
    friends: [
      {
        id: 0,
        name: 'Leticia Navarro',
      },
      {
        id: 1,
        name: 'Michelle Schroeder',
      },
      {
        id: 2,
        name: 'Garcia Villarreal',
      },
    ],
    greeting: 'Hello, Kelsey Melton! You have 5 unread messages.',
    favoriteFruit: 'banana',
  },
];
